/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptographyws1;

/**
 *
 * @author wl2-lam
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("BCH Decode");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        s = jTextField1.getText();
        int s1, s2, s3, s4, s5, s6, k;
        s1 = s2 = s3 = s4 = s5 = s6 = k = 0;
        double p, q, r, j, a, b, f, c, e, g, n, m, h;
        p = q = r = a = b = f = c = e = g = m = h = n = 0;

        for (int i = 0; i < s.length(); i++) {
            d[i] = Integer.parseInt(String.valueOf(s.charAt(i)));
        }
        s1 = (d[0] + d[1] + d[2] + d[3] + d[4] + d[5] + d[6] + d[7] + d[8] + d[9]) % 11;
        s2 = ((d[0] + 2 * d[1] + 3 * d[2] + 4 * d[3] + 5 * d[4] + 6 * d[5] + 7 * d[6] + 8 * d[7] + 9 * d[8] + 10 * d[9]) % 11);
        s3 = ((d[0] + 4 * d[1] + 9 * d[2] + 5 * d[3] + 3 * d[4] + 3 * d[5] + 5 * d[6] + 9 * d[7] + 4 * d[8] + d[9]) % 11);
        s4 = ((d[0] + 8 * d[1] + 5 * d[2] + 9 * d[3] + 4 * d[4] + 7 * d[5] + 2 * d[6] + 6 * d[7] + 3 * d[8] + 10 * d[9]) % 11);
        System.out.println(s1 + "" + s2 + "" + s3 + "" + s4);
        if (s1 == 0 && s2 == 0 && s3 == 0 && s4 == 0) {
            jTextArea1.setText("no error detect");
        } else {

            p = ((s2 * s2) - (s1 * s3));

            p = p % 11;
            if (0 > p) {
                p = neg((int) p);
            }
            q = ((s1 * s4) - (s2 * s3));

            q = q % 11;
            if (0 > q) {
                q = neg((int) q);
            }
            r = ((s3 * s3) - (s2 * s4));
            r = r % 11;
            if (0 > r) {
                r = neg((int) r);
            }
            System.out.println(p + "," + q + "," + r);
            if (p == 0 && q == 0 && r == 0) {
                s5 = divide(s1);
                s6 = ((s2 * s5) % 11);
                d[s6 - 1] = d[s6 - 1] - s1;

                jTextArea1.setText("single error detected with magniude of " + s1 + " in the digit " + s6 + "\nand the revisied number is " + d[0] + "" + d[1] + "" + d[2] + "" + d[3] + "" + d[4] + "" + d[5] + "" + d[6] + "" + d[7] + "" + d[8] + "" + d[9]);

            } else {

                k = (int) ((q * q) - (4 * p * r));
                k = k % 11;
                if (0 > k) {
                    k = neg(k);
                }
                k = sqrt(k);
                System.out.println(k);
                if (k == 0) {
                    jTextArea1.setText("more than 2 error detected");

                } else {
                    j = -q + k;
                    if (j < 0) {
                        j = neg((int) j);
                    }
                    a = (2 * p) % 11;
                    if (a < 0) {
                        a = neg((int) a);
                    }
                    a = divide((int) a);
                    e = (a * j);
                    e = e % 11;
                    c = -q - k;
                    if (c < 0) {
                        c = neg((int) c);
                    }

                    g = (a * c);
                    g = g % 11;
                    m = e - g;
                    if (0 > m) {
                        m = neg((int) m);
                    }

                    n = divide((int) m);
                    b = (e * s1) - s2;
                    if (0 > b) {
                        b = neg((int) b);
                    }

                    b = (b * n);
                    b = b % 11;
                    h = s1 - b;
                    if (h < 0) {
                        h = neg((int) h);
                    }
                    System.out.println(b);

                    System.out.println(e + "," + g + "," + b + "," + h );
                    int op = (int) e;
                    int dp = (int) g;
                    if (d[op - 1] > h) {
                        d[op - 1] = d[op - 1] - (int) h;
                    } else {
                        d[op - 1] = (d[op - 1] + 11) - (int) h;
                    }

                    
                    if (d[dp - 1] > b) {
                        d[dp - 1] = d[dp - 1] - (int) b;
                    } else {
                        System.out.println(d[dp - 1]);
                        d[dp - 1] = (d[dp - 1] + 11) - (int) b;
                    }
                    

                    jTextArea1.setText("two error detected in prosition " + (int) e + " , " + (int) g + " with magnitude " + (int) h + " , " + (int) b + "\n the corrected number is" + d[0] + "" + d[1] + "" + d[2] + "" + d[3] + "" + d[4] + "" + d[5] + "" + d[6] + "" + d[7] + "" + d[8] + "" + d[9]);
                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public int neg(int i) {
        int input = i;
        switch (input) {
            case -1:
                return 10;
            case -2:
                return 9;
            case -3:
                return 8;
            case -4:
                return 7;
            case -5:
                return 6;
            case -6:
                return 5;
            case -7:
                return 4;
            case -8:
                return 3;
            case -9:
                return 2;
            case -10:
                return 1;
            default:
                return 0;
        }
    }

    public int square(int i) {
        int input = i;
        switch (input) {
            case 1:
                return 1;
            case 2:
                return 4;
            case 3:
                return 9;
            case 4:
                return 5;
            case 5:
                return 3;
            case 6:
                return 3;
            case 7:
                return 5;
            case 8:
                return 9;
            case 9:
                return 4;
            case 10:
                return 1;
            default:
                return 0;
        }
    }

    public int divide(int i) {
        int input = i;
        switch (input) {
            case 1:
                return 1;
            case 2:
                return 6;
            case 3:
                return 4;
            case 4:
                return 3;
            case 5:
                return 9;
            case 6:
                return 2;
            case 7:
                return 8;
            case 8:
                return 7;
            case 9:
                return 5;
            case 10:
                return 10;
            default:
                return 0;
        }

    }

    public int sqrt(int i) {
        int input = i;
        switch (input) {
            case 1:
                return 1;

            case 3:
                return 5;
            case 4:
                return 2;
            case 5:
                return 4;

            case 9:
                return 3;

            default:
                return 0;
        }
    }

    private static String s = "";
    private final int[] d = new int[16];

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
